source 'https://rubygems.org'

gem 'sinatra'
gem 'http'

group :test, :development do
  gem 'byebug'
end

group :development do
  gem 'sinatra-contrib'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
end